language: php
php:
- 7.2
before_script:
#- composer install
script: echo 'none'
deploy:
  provider: heroku
  app: curso-github-cefire
  on: master
  skip_cleanup: true
  api_key:
    secure: MP5diWbyU+KRbeac3XHCa2ezG/3ek5qIIzAw4xjLJ9fO4KgugzqOSvStjOANXY43E+Og7D5XpByq6SSBMj3q/TdM59hmtfNWT6zpqGL8xF7uyTAICm/T8NZGWOBdQ+J4UB5z4qrzqf2LLYyucTdsQobUTASSqj1HuiFJ2xyf4QHalzsa3E3hOf/TIQT6hMuVlVskQthGmVW0QCKCocE3cMZkiQFgT7VVSN81KQFkn8duOT4si//Yp/+yYgc8R921mQCQVUScySc72n6/+Q+GY6YORoRsaJl5UVcXEHfLXOcxMkenCt2MQL9qJtH19XWK9k2K3M6J9a5HEowMTJT3NxJrWpDfmDQRRDqMhn6VHnQijLyUKm6/qYv1nJcytu8AjLmBWOWvUmxy0Lu8bHLv8YxFkdKlkzb4uMC/kR1FvNVkPMNGSAndVETdCkHbIEEE6Scc0ZwCG7bdtWRkAegM8xAbvKbzSXUonAZiKuLYSEF1EsFynGKB9B+ZR+wP0GZjpm+WKFPbvTbx4hpkmq3B2puF9C2xe9B4O+jKEg041ycHzQ1AUO675kdNbBDG56Qa9vc+JkFdHCc26RTHx7wnNY9oUih5rCrzaIgkSMnRvjcPEG/XOQaC4Ehy2uzpKncsie57K2Jbj6dy22Trm07hPtlXteeDruvsjW98/4Xl2nw=

